# NUMPY 

### Contents

### 1. Introduction to NumPy

    1.1 What is NumPy?
    
    1.2 Why Use NumPy in Data Science?
    


### 2. Installing and Importing NumPy

    2.1 Installation Instructions
    
    2.2 Importing NumPy
    
    
    
### 3. NumPy Arrays

    3.1 Creating NumPy Arrays
    
    3.2 Array Attributes
    
    3.3 Indexing and Slicing Arrays
    
    3.4 Array Operations 
    
    3.5 Broadcasting
    
### 4. Array Manipulation

    4.1 Reshaping Arrays
    
    4.2 Joining and Splitting Arrays
    
    4.3 Changing Array Data Types

    4.4 Sorting and Searching Arrays
    
    

### 5. Mathematical Functions
    
    5.1 Basic Mathematical Operations

    5.2 Trigonometric Functions

    5.3 Exponential and Logarithmic Functions

    5.4 Statistical Functions

    5.5 Linear Algebra Operations



### 6. Array Input and Output

    6.1 Saving and Loading Arrays

    6.2 Text File Input and Output

    6.3 Binary File Input and Output

    6.4 Compressed File Input and Output




### 7. Advanced NumPy Features

    7.1 Broadcasting in Depth

    7.2 Array Manipulation Tricks

    7.3 Fancy Indexing and Boolean Masking

    7.4 Structured Arrays

    7.5 Universal Functions



### 8. Performance Tips and Best Practices
    
    8.1 Vectorization
    
    8.2 Memory Efficiency
    
    8.3 Use NumPy Functions Instead of Loops



### 9. Conclusion


--------------------------------------------------------------------------------------------------------------------------------
********************************************************************************************************************************
--------------------------------------------------------------------------------------------------------------------------------

# 1. Introduction to NumPy
#### 1.1 What is NumPy?
NumPy (Numerical Python) is an open-source Python library
that provides powerful tools for performing numerical
computations and working with multi-dimensional arrays. It
serves as the foundation for many other scientific computing
libraries in Python and is widely used in data science, machine
learning, and scientific research.

#### 1.2 Why Use NumPy in Data Science?

* Efficient array operations: NumPy provides fast and efficientimplementations of mathematical operations on arrays,making it suitable for large-scale data processing.

* Multi-dimensional arrays: NumPy arrays allow for efficient storage and manipulation of multi-dimensional data, such as matrices or tensors.

* Broadcasting: NumPy supports broadcasting, which enables operations between arrays of different shapes,making code concise and readable.

* Integration with other libraries: NumPy seamlessly integrates with other data science libraries such as Pandas,Matplotlib, and scikit-learn, providing a comprehensivecosystem for data analysis and machine learning.


# 2. Installing and Importing NumPy
#### 2.1 Installation Instructions



In [12]:
pip install numpy 


Note: you may need to restart the kernel to use updated packages.


In [11]:
pip install --upgrade pip

                                              0.0/2.1 MB ? eta -:--:--
                                              0.0/2.1 MB ? eta -:--:--
                                              0.0/2.1 MB 445.2 kB/s eta 0:00:05
                                              0.0/2.1 MB 281.8 kB/s eta 0:00:08
     -                                        0.1/2.1 MB 409.6 kB/s eta 0:00:05
     -                                        0.1/2.1 MB 403.5 kB/s eta 0:00:05
     --                                       0.1/2.1 MB 481.4 kB/s eta 0:00:05
     ---                                      0.2/2.1 MB 618.3 kB/s eta 0:00:04
     ----                                     0.2/2.1 MB 722.1 kB/s eta 0:00:03
     -----                                    0.3/2.1 MB 770.1 kB/s eta 0:00:03
     ------                                   0.4/2.1 MB 827.0 kB/s eta 0:00:03
     -------                                  0.4/2.1 MB 859.0 kB/s eta 0:00:02
     --------                                 0.5/2.1 MB 8

#### 2.2 Importing NumPy
'np' is and alias name for NumPy to prevent writting Numpy everytime in the code.

In [13]:
import numpy as np

# 3. NumPy Arrays
#### 3.1 Creating NumPy Arrays


In [14]:
# Using the numpy.array() function

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [18]:
# Using the numpy.arange() function: 

arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [23]:
# Using the numpy.zeros() and numpy.ones() functions

zeros = np.zeros((3,3))
print(zeros)

print()
 
ones = np.ones((2,6))
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 3.2 Array Attributes

* shape: Returns a tuple representing the size of each dimension of the array.

* dtype: Returns the data type of the array elements.

* ndim: Returns the number of array dimensions.

* size: Returns the total number of elements in the array.

* itemsize: Returns the size in bytes of each array element.


In [29]:
np.shape(zeros)

(3, 3)

In [36]:
arr.dtype

dtype('int32')

In [39]:
np.ndim(zeros)

2

In [33]:
np.size(zeros)

9

In [37]:
arr.itemsize

4

#### 3.3 Indexing and Slicing Arrays


In [43]:
ar = np.arange(1,20,2)
ar

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [44]:
ar[0]

1

In [46]:
ar[-1]

19

In [47]:
ar[2:5]

array([5, 7, 9])

#### 3.4 Array Operations 


In [49]:
ar1 = np.arange(5,20,2)
ar1

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [51]:
ar2 = np.arange(20,35,2)
ar2

array([20, 22, 24, 26, 28, 30, 32, 34])

In [53]:
# Add
print(ar1+ar2)

[25 29 33 37 41 45 49 53]


In [58]:
# Subtraction
print(ar1-ar2)

[-15 -15 -15 -15 -15 -15 -15 -15]


In [60]:
# Multiplication
print(ar1*ar2)

[100 154 216 286 364 450 544 646]


In [62]:
# Division
print(ar1/ar2)

[0.25       0.31818182 0.375      0.42307692 0.46428571 0.5
 0.53125    0.55882353]


In [63]:
# Division
print(ar1//ar2)

[0 0 0 0 0 0 0 0]


In [64]:
# Mod
print(ar1%ar2)

[ 5  7  9 11 13 15 17 19]


#### 3.5 Broadcasting

Allows operations between arrays having different shape

In [69]:
a = np.array([[1,2,3],[4,5,6]])
scalar = 4

print(a*scalar)

[[ 4  8 12]
 [16 20 24]]


# 4. Array Manipulation

   #### 4.1 Reshaping Arrays
   1. reshape()
   2. flatten()
   3. ravel()


In [70]:
ar1.reshape(4,2)

array([[ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [72]:
ar2.flatten()

array([20, 22, 24, 26, 28, 30, 32, 34])

In [73]:
ar1.ravel()

array([ 5,  7,  9, 11, 13, 15, 17, 19])

#### 4.2 Joining and Splitting Arrays

In [74]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [76]:
concat = np.concatenate((a1,a2))
concat

array([1, 2, 3, 4, 5, 6])

####  4.3 Changing Array Data Types 

* astype()

In [78]:
arr = np.array([1,2,3,4,5],dtype = np.float64)
arr

array([1., 2., 3., 4., 5.])

In [80]:
new = arr.astype(np.int32)
new

array([1, 2, 3, 4, 5])

In [83]:
new.dtype

dtype('int32')

#### 4.4 Sorting and Searching Arrays

1. Sorting
* sort()
* argsort()

2. Searching
* where() --> returns indices
* seachsorted()

In [85]:
arr = np.array([4,2,1,3,5])
new_SortedArray = np.sort(arr)
new_SortedArray

array([1, 2, 3, 4, 5])

In [93]:
b = np.where(arr<3)
b

(array([1, 2], dtype=int64),)

# 5. Mathematical Functions
    
#### 5.1 Basic Mathematical Operations
1. add()
2. subtract()
3. multiply()
4. divide()


In [99]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [100]:
# add()
arr+5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [101]:
# subtract()
arr-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
# multiply()
arr*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [103]:
# divide()
arr/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

####    5.2 Trigonometric Functions

1. sin()
2. cos()
3. tan()
4. arcsin()
5. arccos()
6. arctan()


In [105]:
# sin()
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [106]:
# cos()
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [107]:
np.tan(arr)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])

#### 5.3 Exponential and Logarithmic Functions
1. exp()
2. log()
3. log10()


In [110]:
a = np.array([1,10,100])

np.exp(a)

array([2.71828183e+00, 2.20264658e+04, 2.68811714e+43])

In [112]:
np.log(a)

array([0.        , 2.30258509, 4.60517019])

In [111]:
np.log10(a)

array([0., 1., 2.])

#### 5.4 Statistical Functions
1. min()
2. max()
3. mean()
4. median()
5. std()
6. var()


In [117]:
arr = np.arange(1,10)
np.min(arr)

1

In [118]:
np.max(arr)

9

In [120]:
np.mean(arr)

5.0

In [121]:
np.median(arr)

5.0

In [122]:
np.std(arr)

2.581988897471611

In [123]:
np.var(arr)

6.666666666666667

#### 5.5 Linear Algebra Operations
1. dot()
2. transpose()
3. inverse()
4. eig()

In [126]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.dot(mat,mat)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [127]:
np.transpose(mat)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# 6. Array Input and Output
#### 6.1 Saving and Loading Arrays


In [131]:
ar = np.array([1,2,3,4,5])

np.save('array.npy',ar)

loader_arr = np.load('array.npy')

loader_arr

array([1, 2, 3, 4, 5])

#### 6.2 Text File Input and Output

In [134]:
ar = np.array([1,2,3,4,5])

np.savetxt('array.txt',ar)

loader_arr = np.loadtxt('array.txt')

loader_arr

array([1., 2., 3., 4., 5.])

#### 6.3 Binary File Input and Output
1. np.save()
2. np.load()

In [135]:
ar = np.array([1,2,3,4,5])

np.save('array.npy',ar)

loader_arr = np.load('array.npy')

loader_arr

array([1, 2, 3, 4, 5])

#### 6.4 Compressed File Input and Output
NumPy allows you to save and load compressed arrays using
np.savez() and np.load() with the .npz file extension. This is
useful for saving memory and reducing storage space.


In [136]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [139]:
np.savez('array.npz',x=x,y=y)
load_data = np.load('array.npz')

print(load_data['x'])
print(load_data['y'])

[1 2 3]
[4 5 6]


# 7. Advanced NumPy Features

#### 7.1 Broadcasting in Depth
Broadcasting is a powerful feature of NumPy that allows arrays
of different shapes to be combined in arithmetic operations.
NumPy automatically applies broadcasting rules to make the
arrays compatible for the operation.


In [157]:
c = np.array([[1,2,3],[4,5,6]])
d = np.array([10,20,30]) 

result = c + d 
result

array([[11, 22, 33],
       [14, 25, 36]])

#### 7.2 Array Manipulation Tricks

In [162]:
c = np.array([[1,2,3],[4,5,6]])

transposed = c.T
repeated = np.repeat(c,2,axis = 0)
stacked = np.stack((c,c),axis=1)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [161]:
transposed

array([[1, 4],
       [2, 5],
       [3, 6]])

In [163]:
repeated

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [165]:
stacked

array([[[1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [4, 5, 6]]])

#### 7.3 Fancy Indexing and Boolean Masking
c = np.array([[1,2,3],[4,5,6]])

In [169]:
e = np.array([1,2,3,4,5])

indices = np.array([0,2,4])
print(e[indices])


[1 3 5]


In [171]:
mask = e > 2
mask

array([False, False,  True,  True,  True])

#### 7.4 Structured Arrays

In [175]:
dt = np.dtype([('name',np.str_,16),('age',np.int32),('salary',np.float64)])
arr = np.array([('John',25,5000.0),('Alice',30,6000.0)], dtype=dt)

print(arr['name'])
print(arr['age'])
print(arr['salary'])

['John' 'Alice']
[25 30]
[5000. 6000.]


#### 7.5 Universal Functions

In [178]:
a = np.array([1,2,3])

print(np.add(a,2))

[3 4 5]


In [179]:
print(np.multiply(a,5))

[ 5 10 15]


In [180]:
print(np.sqrt(a))

[1.         1.41421356 1.73205081]


# 8. Performance Tips and Best Practices
    
#### 8.1 Vectorization

In [144]:
# Non Vectorised Approach

p = np.array([1,2,3])
q = np.array([4,5,6])
result = np.zeros(3)

for i in range(3):
    result[i] = p[i] + q[i]
    
result

array([5., 7., 9.])

In [145]:
# Vectorised Approach

result = p + q

result

array([5, 7, 9])

#### 8.2 Memory Efficiency


In [152]:
p = np.array([1,2,3]) 
q = p 

view = p.view()  # no additional memory

copy = p.copy()  # using additional memory

In [150]:
view

array([1, 2, 3])

In [151]:
copy

array([1, 2, 3])

####   8.3 Use NumPy Functions Instead of Loops

In [155]:
s = np.array([1,2,3,4,5])
# Non Vectorised Approach
total = 0 
for num in s:
    total+=num
    
total

15

In [156]:
# Vectorised Approach
total = np.sum(s)
total

15

# 9. Conclusion


NumPy is a powerful library for data science, providing
efficient and flexible data structures and functions for
numerical computing.

With this knowledge, you can leverage NumPy
to perform various data science tasks efficiently and
effectively. 

Happy coding!!